on:
  push:
    branches:
      - "main"
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-step-go@v3
      with:
        go-version '>=1.19.2'
    - uses: actions/checkout@v3
    - run: go test ./... -converprofile=coverage.out
    -name: report coverage
      uses: k1oW/octocov-action@v0